name: '🛠 Feature Request'
description: Suggest a new feature or idea for CodeSnap
labels: feature request
body:
  - type: textarea
    id: description
    attributes:
      label: Please describe the feature that you want to propose
      description: A clear and concise description of what you want to happen in CodeSnap.
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: |
        What problem would this feature solve or how would it improve the user experience in CodeSnap? Please include context about how this feature would be used.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature important?
      description: Why do you believe this feature is valuable to CodeSnap users? What are the benefits or impact?
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: |
        If you have any additional information that would help in understanding your feature request (e.g., examples, design ideas, or related features), please provide it here.
